version: 3
profiles: []
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c: []
  copy: []
  paste:
    - Alt-V
  select-all: []
  clear: []
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  home: []
  end: []
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-line: []
  delete-next-word: []
  search: []
  pane-focus-all: []
  focus-all-tabs: []
  scroll-to-top: []
  scroll-up: []
  scroll-down: []
  scroll-to-bottom: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings: []
  serial: []
  restart-serial-session: []
  new-tab: []
  new-window: []
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - Ctrl-Shift-F
  close-tab: []
  reopen-tab: []
  toggle-last-tab: []
  rename-tab: []
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  explode-tab: []
  combine-tabs: []
  tab-1: []
  tab-2: []
  tab-3: []
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right: []
  split-bottom: []
  split-left: []
  split-top: []
  pane-nav-right: []
  pane-nav-down: []
  pane-nav-up: []
  pane-nav-left: []
  pane-nav-previous: []
  pane-nav-next: []
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize: []
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile: []
  profile-selector: []
  command-selector: []
terminal:
  searchOptions: {}
  colorScheme: &ref_0
    name: ayu
    foreground: '#e9e9e9'
    background: '#000000'
    cursor: '#f29718'
    colors:
      - '#000000'
      - '#ff3333'
      - '#b8cc52'
      - '#e7c547'
      - '#36a3d9'
      - '#f07178'
      - '#95e6cb'
      - '#ffffff'
      - '#323232'
      - '#ff6565'
      - '#eafe84'
      - '#fff779'
      - '#68d5ff'
      - '#ffa3aa'
      - '#c7fffd'
      - '#ffffff'
  customColorSchemes:
    - name: Molokai
      foreground: '#bbbbbb'
      background: '#121212'
      cursor: '#ffd3d3'
      colors:
        - '#121212'
        - '#fa2573'
        - '#98e123'
        - '#dfd460'
        - '#42a5f5'
        - '#8700ff'
        - '#80deea'
        - '#eceff1'
        - '#eceff1'
        - '#f6669d'
        - '#b1e05f'
        - '#fff26d'
        - '#b2ebf2'
        - '#af87ff'
        - '#51ceff'
        - '#ffffff'
    - *ref_0
  font: Cica
  fontSize: 16
  minimumContrastRatio: 5
  cursorBlink: false
  warnOnMultilinePaste: false
  hideTabIndex: true
  altIsMeta: true
ssh: {}
configSync:
  parts:
    vault: false
    appearance: false
    hotkeys: false
clickableLinks: {}
accessibility: {}
appearance:
  theme: Follow the color scheme
  spaciness: 0.6
  dockScreen: 2528732444
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
